version: '3.7'

services:
    whatslog:
        container_name: whatslog
        build: .
        restart: always
        env_file:
            - .env
        volumes:
            - .:/usr/app
            - /usr/app/node_modules
            - ./config.json:/app/config.json
        depends_on:
            - db
        links:
            - db
        ports:
            - ${APP_PORT}:${APP_PORT}
        command: npm run start
    db:
        image: mongo:4.4.6
        container_name: db
        restart: always
        ports:
            - '${DB_PORT}:27017'
        environment:
            MONGO_INITDB_DATABASE: ${DB_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
        env_file:
            - .env
        volumes:
            - dbdata-volume:/data/db
            
volumes:
    dbdata-volume:
    vault-data: